version: 2.0.{build}

build_script:
- genie.exe vs2015 genie.lua
- cd Build/vs2015
- MsBuild Brofiler_vs2015.sln /t:Rebuild /p:Configuration=Release
- cd ../../Brofiler
- MsBuild Brofiler.sln /t:Rebuild /p:Configuration=Release