version: 2.0.{build}

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - nuget restore BrofilerApp/BrofilerApp_vs2015.sln
  
build_script:
  - Tools\Windows\premake5.exe vs2015
  - cd Build/vs2015
  - MsBuild Brofiler.sln /t:Rebuild /p:Configuration=%CONFIGURATION%
  - cd ../../BrofilerApp
  - MsBuild BrofilerApp_vs2015.sln /t:Rebuild /p:Configuration=%CONFIGURATION%