version: 1.0.{build}

build_script:
- Tools\Windows\premake5.exe vs2015
- cd BrofilerApp
- MsBuild BrofilerApp_vs2017.sln /t:Rebuild /p:Configuration=Release
- cd ..
- cd Build/vs2015
- MsBuild Brofiler.sln /t:Rebuild /p:Configuration=Release

test_script:
- echo Brofiler test
