version: 1.0.{build}

build_script:
- genie.exe vs2012 genie.lua
- cd Brofiler
- MsBuild Brofiler_vs2012.sln /t:Rebuild /p:Configuration=Release
- cd ..
- cd Build/vs2012
- MsBuild Brofiler.sln /t:Rebuild /p:Configuration=Release

test_script:
- echo Brofiler test
